#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:

      #jpa ddl-auto
      ddl-auto: update
    show-sql: true

    #jpa format
    properties:
      hibernate:
        format_sql: true

  #log
  output:
    ansi:
      enabled: always

  #Redis
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis

  #multipart
  servlet:
    multipart:
      enabled: true
      max-request-size: 40MB
      max-file-size: 40MB
      file-size-threshold: 100MB

  #send-email
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'happywelfarebox@gmail.com'
    password: 'gihftlfbtgdcdbuo'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #OAuth2
  security:
    oauth2:
      client:
        registration:
          #naver
          naver:
            client-name: Naver
            client-id: studRFKgw1vmCmfBnAMM
            client-secret: kaZiVGKsZj
            redirect-uri: http://localhost:10000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,mobile

          #kakao
          kakao:
            client-id: 00e7d9a870a6d913b60d3ec64246794a
            client-secret: cgpvjCsfe8DWZx6PcUi1uTw2gZHy5uBD
            redirect-uri: http://localhost:10000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email
            client_name: kakao

        provider:
          #naver
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          #kakao
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account